# **Lista de exercícios 9** *(Heitor Hayashi Ferrairo)*, caso tenha algum comentário ou encontre algum erro me notifique por gentileza!

### **Testes**

In [ ]:
import sqlite3

conexao_teste = sqlite3.connect("banco_teste.db")
cursor = conexao_teste.cursor()

cursor.execute("""
CREATE TABLE IF NOT EXISTS vendedores (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  nome TEXT NOT NULL,
  email TEXT UNIQUE
);
""")

conexao_teste.commit()

try:
  cursor.execute("""
  INSERT INTO vendedores (nome, email)
  VALUES (?, ?)
  """, ("Joana", "joana@email.com"))
  conexao_teste.commit()
  print("Registro inserido com sucesso!")


except sqlite3.IntegrityError:
  print("Erro: E-mail já cadastrado!")

cursor.execute("SELECT * FROM vendedores")
print("\nLista de vendedores:")

for vendedor in cursor.fetchall():
  print(vendedor)

if conexao_teste:
  conexao_teste.close()
  print("\nConexão encerrada.")

### **Exercícios**

Parte 1 – Conexão e estruturação
1. Crie um novo banco de dados chamado loja.db.
2. Crie uma tabela produtos com os campos:
*   id chave primária, autoincremento;
*   nome – texto, obrigatório;
*   preco – número real.

3. Insira pelo menos 3 produtos na tabela usando uma função com try/except para capturar erros de inserção.

In [ ]:
import sqlite3

def conectar():
  try:
    conexao = sqlite3.connect('loja.db')
    return conexao
  except sqlite3.Error as e:
    print(f"Erro tentando conectar: {e}")

def criar_tabela():
  conn = conectar()
  if not conn:
    return

  try:
    cursor = conn.cursor()
    cursor.execute("""
      CREATE TABLE IF NOT EXISTS produtos (
        id INTEGER PRIMARY KEY AUTOINCREMENT,
        nome TEXT NOT NULL,
        preco REAL
      )
    """)
    conn.commit()
    print("Tabela criada com sucesso!")
  except sqlite3.Error as e:
      print(f"Erro ao criar tabela: {e}")
  finally:
      conn.close()

def inserir_produto(nome, preco):
  conn = conectar()
  if not conn:
    return

  try:
    cursor = conn.cursor()
    cursor.execute("INSERT INTO produtos (nome, preco) VALUES (?, ?)", (nome, preco))
    conn.commit()
    print(f"Produto {nome} inserido com sucesso!")
  except sqlite3.Error as e:
    print(f"Erro ao inserir produto: {e}")
  finally:
    conn.close()


criar_tabela()
produtos = [
  ("Notebook", 3500.00),
  ("Smartphone", 1500.00),
  ("Tablet", 800.00)
]

for nome, preco in produtos:
  inserir_produto(nome, preco)

Tabela criada com sucesso!
Produto Notebook inserido com sucesso!
Produto Smartphone inserido com sucesso!
Produto Tablet inserido com sucesso!

Parte 2 – Consultas e leitura de dados
1. Liste todos os produtos cadastrados com uma função que trata erros de leitura.

2. Faça uma consulta que mostre apenas produtos com preço acima de R$ 100.

3. Teste o retorno de uma tabela vazia (faça uma busca que não retorne nada) e trate isso no código, mostrando uma mensagem como “Nenhum produto encontrado”.

In [ ]:
def listar_produtos():
  conn = conectar()
  if not conn:
    return

  try:
    cursor = conn.cursor()
    cursor.execute("SELECT * FROM produtos")
    resultados = cursor.fetchall()

    if not resultados:
      print("Nenhum produto cadastrado.")
      return

    print("\nProdutos cadastrados:")
    for produto in resultados:
      print(f"ID: {produto[0]} | Nome: {produto[1]} | Preço: R${produto[2]:.2f}")

  except sqlite3.Error as e:
    print(f"Erro ao listar produtos: {e}")
  finally:
    conn.close()

def produtos_acima_100():
  conn = conectar()
  if not conn:
    return

  try:
    cursor = conn.cursor()
    cursor.execute("SELECT * FROM produtos WHERE preco > 100")
    resultados = cursor.fetchall()

    if not resultados:
      print("Nenhum produto acima de R$100 encontrado.")
      return

    print("\nProdutos acima de R$100:")
    for produto in resultados:
      print(f"ID: {produto[0]} | Nome: {produto[1]} | Preço: R${produto[2]:.2f}")

  except sqlite3.Error as e:
    print(f"Erro na consulta: {e}")
  finally:
    conn.close()

listar_produtos()
produtos_acima_100()

Produtos cadastrados:
ID: 1 | Nome: Notebook | Preço: R$3500.00
ID: 2 | Nome: Smartphone | Preço: R$1500.00
ID: 3 | Nome: Tablet | Preço: R$800.00
ID: 4 | Nome: Notebook | Preço: R$3500.00
ID: 5 | Nome: Smartphone | Preço: R$1500.00
ID: 6 | Nome: Tablet | Preço: R$800.00
ID: 7 | Nome: Notebook | Preço: R$3500.00
ID: 8 | Nome: Smartphone | Preço: R$1500.00
ID: 9 | Nome: Tablet | Preço: R$800.00
ID: 10 | Nome: Notebook | Preço: R$3500.00
ID: 11 | Nome: Smartphone | Preço: R$1500.00
ID: 12 | Nome: Tablet | Preço: R$800.00
ID: 13 | Nome: Notebook | Preço: R$3500.00
ID: 14 | Nome: Smartphone | Preço: R$1500.00
ID: 15 | Nome: Tablet | Preço: R$800.00
ID: 16 | Nome: Notebook | Preço: R$3500.00
ID: 17 | Nome: Smartphone | Preço: R$1500.00
ID: 18 | Nome: Tablet | Preço: R$800.00
ID: 19 | Nome: Notebook | Preço: R$3500.00
ID: 20 | Nome: Smartphone | Preço: R$1500.00
ID: 21 | Nome: Tablet | Preço: R$800.00

Produtos acima de R$100:
ID: 1 | Nome: Notebook | Preço: R$3500.00
ID: 2 | Nome: Smartphone | Preço: R$1500.00
ID: 3 | Nome: Tablet | Preço: R$800.00
ID: 4 | Nome: Notebook | Preço: R$3500.00
ID: 5 | Nome: Smartphone | Preço: R$1500.00
ID: 6 | Nome: Tablet | Preço: R$800.00
ID: 7 | Nome: Notebook | Preço: R$3500.00
ID: 8 | Nome: Smartphone | Preço: R$1500.00
ID: 9 | Nome: Tablet | Preço: R$800.00
ID: 10 | Nome: Notebook | Preço: R$3500.00
ID: 11 | Nome: Smartphone | Preço: R$1500.00
ID: 12 | Nome: Tablet | Preço: R$800.00
ID: 13 | Nome: Notebook | Preço: R$3500.00
ID: 14 | Nome: Smartphone | Preço: R$1500.00
ID: 15 | Nome: Tablet | Preço: R$800.00
ID: 16 | Nome: Notebook | Preço: R$3500.00
ID: 17 | Nome: Smartphone | Preço: R$1500.00
ID: 18 | Nome: Tablet | Preço: R$800.00
ID: 19 | Nome: Notebook | Preço: R$3500.00
ID: 20 | Nome: Smartphone | Preço: R$1500.00
ID: 21 | Nome: Tablet | Preço: R$800.00

Desafio final – CRUD robusto

Implemente um script chamado sistema_clientes.py com as seguintes funções:

• conectar() – com tratamento de erro na conexão;


• criar_tabela() – que garante que a tabela só será criada uma vez;

• inserir_cliente(nome, email) – com verificação de duplicidade;

• listar_clientes() – com tratamento de erro e caso vazio;

• atualizar_email(nome, novo_email) – que informe se o cliente não foi encontrado;

• deletar_cliente(nome) – que não apague silenciosamente.
Teste:

• Inserir dois clientes com o mesmo email;

• Deletar um cliente inexistente;

• Atualizar email de um nome que não existe.

In [ ]:
import sqlite3

def conectar():
  try:
    return sqlite3.connect('clientes.db')
  except sqlite3.Error as e:
    print(f"Erro de conexão: {e}")
    return

def criar_tabela():
  conn = conectar()
  if not conn:
    return

  try:
    cursor = conn.cursor()
    cursor.execute("""
      CREATE TABLE IF NOT EXISTS clientes (
        id INTEGER PRIMARY KEY AUTOINCREMENT,
        nome TEXT NOT NULL,
        email TEXT UNIQUE
      )
    """)
    conn.commit()
    print("Tabela clientes criada/verificada")
  except sqlite3.Error as e:
    print(f"Erro ao criar tabela: {e}")
  finally:
    conn.close()

def inserir_cliente(nome, email):
  conn = conectar()
  if not conn:
    return

  try:
    cursor = conn.cursor()
    cursor.execute(
      "INSERT INTO clientes (nome, email) VALUES (?, ?)",
      (nome, email)
    )
    conn.commit()
    print(f"Cliente {nome} cadastrado!")
  except sqlite3.IntegrityError:
    print(f"ERRO: Email {email} já existe!")
  except sqlite3.Error as e:
    print(f"Erro ao inserir: {e}")
  finally:
    conn.close()

def listar_clientes():
  conn = conectar()
  if not conn:
    return

  try:
    cursor = conn.cursor()
    cursor.execute("SELECT * FROM clientes")
    clientes = cursor.fetchall()

    if not clientes:
      print("\nNenhum cliente cadastrado")
      return

    print("\nLista de Clientes:")
    for cliente in clientes:
      print(f"ID: {cliente[0]} | Nome: {cliente[1]} | Email: {cliente[2]}")
  except sqlite3.Error as e:
    print(f"Erro ao listar: {e}")
  finally:
    conn.close()

def atualizar_email(nome, novo_email):
  conn = conectar()
  if not conn:
    return

  try:
    cursor = conn.cursor()
    cursor.execute(
      "UPDATE clientes SET email = ? WHERE nome = ?",
      (novo_email, nome)
    )

    if cursor.rowcount == 0:
      print(f"Cliente '{nome}' não encontrado!")
    else:
      conn.commit()
      print(f"Email de '{nome}' atualizado para '{novo_email}'")
  except sqlite3.IntegrityError:
    print(f"ERRO: Email '{novo_email}' já existe!")
  except sqlite3.Error as e:
    print(f"Erro ao atualizar: {e}")
  finally:
    conn.close()

def deletar_cliente(nome):
  conn = conectar()
  if not conn:
    return

  try:
    cursor = conn.cursor()
    cursor.execute("DELETE FROM clientes WHERE nome = ?", (nome,))

    if cursor.rowcount == 0:
      print(f"Cliente '{nome}' não encontrado!")
    else:
      conn.commit()
      print(f"Cliente '{nome}' removido com sucesso!")
  except sqlite3.Error as e:
    print(f"Erro ao deletar: {e}")
  finally:
    conn.close()

criar_tabela()
inserir_cliente("Maria", "maria@email.com")
inserir_cliente("Carlos", "carlos@email.com")
# listar_clientes()
inserir_cliente("Outra Maria", "maria@email.com")
atualizar_email("Carlos", "carlos.novo@email.com")
listar_clientes()
atualizar_email("Nulo", "erro@email.com")
deletar_cliente("Maria")
deletar_cliente("Ninguem")
listar_clientes()

Tabela clientes criada/verificada
Cliente Maria cadastrado!
ERRO: Email carlos@email.com já existe!
ERRO: Email maria@email.com já existe!
ERRO: Email 'carlos.novo@email.com' já existe!

Lista de Clientes:
ID: 2 | Nome: Carlos | Email: carlos.novo@email.com
ID: 4 | Nome: Carlos | Email: carlos@email.com
ID: 12 | Nome: Maria | Email: maria@email.com
Cliente 'Nulo' não encontrado!
Cliente 'Maria' removido com sucesso!
Cliente 'Ninguem' não encontrado!

Lista de Clientes:
ID: 2 | Nome: Carlos | Email: carlos.novo@email.com
ID: 4 | Nome: Carlos | Email: carlos@email.com